### ISSUE TITLE
Library contains files under GPL

### ISSUE THREAD

**Issue by lategoodbye** [cryptotronix/libcrypti2c#21]
Hi, this is a very nice library. I noticed that the following files contains the notice that they are part of EClet and under the GPL:

```
src/atsha204_command.c
src/atsha204_command.h
src/command_util.h
src/otp.c
```

This looks like a copy & paste issue and i hope this could be moved to LGPL. As a motivation i'm interested to provide the implementation of missing commands like PrivWrite 0x46 and SHA 0x47.

**Comment by jbdatko** [comment]
The intention is for LGPL so this was sloppy copy and paste on my part. This is fixed on master now. Thank you!

**Comment by lategoodbye** [comment]
So finally COPYING (GPL) could be replace by COPYING.LESSER (LGPL)?

**Comment by jbdatko** [comment]
Yes... :) I'll try to hop back on and change it soon ish. If you see any
others fell free to PR them as well.

To be clear, I mean for everything is this repo to be LGPL.

Apparently there is a GNU program somewhere to help with header licensing,
I should try that at some point.
